language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - yarn lint
  - yarn test
before_deploy:
  - yarn build
after_deploy:
  - ./post_deploy.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master
